### ISSUE TITLE
Avoid using ghostscript 9.27

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/2019-unavco-course#13]
The latest release of ghostscript (9.27) has serious bugs (see https://github.com/GenericMappingTools/gmt/issues/880 for details), which shouldn't and can't be used for GMT plotting.

We should tell users to check if their ghostscript version is 9.27. If they're unlucky, they have to install an old version of ghostscript themselves.

For Linux and Windows, the ghostscript official website provides the pre-compiled packages, so users can choose the 9.26 or any other version.

For macOS, the ghostscript from homebrew is 9.27, which is buggy. I've made a PR (https://github.com/Homebrew/homebrew-core/pull/41678) which includes the official patch. Unluckily, it doesn't pass the homebrew CI tests, although it works for me locally. Homebrew users need to take more steps to install a bug-free ghostscript.

**Comment by leouieda** [comment]
Right, we forgot about that. Thanks for point it out @seisman!

Our linux instructions are conda based, which still uses 9.22, so that shouldn't be a problem. 

Mac: is there a way to specify a version number for brew? Like `brew install ghostscript==9.26`? That would solve the problem there.

Windows: the instructions should say direct users to download `gs926aw64.exe` from https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/tag/gs926 instead of the current link.

**Comment by PaulWessel** [comment]
But note that at least for macports they quickly fixed the problem (says 9.27 but updated on June 27).  I don't know the situation for brew and fink, of course.

**Comment by PaulWessel** [comment]
Heading home but will check for more activity later...

**Comment by leouieda** [comment]
We could change the instructions to use macports instead of brew if that
helps.

**Comment by PaulWessel** [comment]
Need to check if brew version is fixed. I think Bree is simpler than
MacPorts...

**Comment by alebcay** [comment]
> Mac: is there a way to specify a version number for brew? Like brew install ghostscript==9.26? That would solve the problem there.

There is no easy way to do it, Homebrew only supports installing the most recent version. The `brew extract` command however provides ways to recover old installation script versions from the Git repo history that you can manually install from.

**Comment by seisman** [comment]
Homebrew updated its ghostscript 9.27 a few minutes ago . It's still ghostscript 9.27, but with the problem in GenericMappingTools/gmt#880 fixed.

Now it's OK to use homebrew to install ghostscript.

**Comment by PaulWessel** [comment]
Good news, wonder if anyone is using fink out there and what the story is.

**Comment by seisman** [comment]
From what I see, I think fink provides 9.25 (http://pdb.finkproject.org/pdb/package.php/ghostscript) or 9.26 (https://github.com/fink/fink-distributions/blob/master/10.9-libcxx/stable/main/finkinfo/text/ghostscript.info).

**Comment by leouieda** [comment]
Great! Thanks @alebcay for the input

**Comment by leouieda** [comment]
Can we mark this as solved?
