### ISSUE TITLE
installation of gmt6 using conda 

### ISSUE THREAD

**Issue by mohseniaref-InSAR** [GenericMappingTools/2019-unavco-course#15]
**Operating system**:
Ubuntu

**The commands you ran or things you installed**:
conda install gmt=6.0.0rc2 -c conda-forge/label/dev -c conda-forge

**Which step is giving you trouble**:

**What is the exact error message (copy and paste it)**:
 conda install gmt=6.0.0rc2 -c conda-forge/label/dev -c conda-forge
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - gmt=6.0.0rc2

Current channels:

  - https://conda.anaconda.org/conda-forge/label/dev/linux-32
  - https://conda.anaconda.org/conda-forge/label/dev/noarch
  - https://conda.anaconda.org/conda-forge/linux-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-32
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by seisman** [comment]
Are you using a 32-bit Linux? Could you post the output of `uname -a`?

**Comment by mohseniaref-InSAR** [comment]
I fixed the issue by replacing miniconda to 64-bit version but it seems it doesn't work for 32-bit version

**Comment by seisman** [comment]
Yes, there're no 32-bit packages from conda.

**Comment by mohseniaref-InSAR** [comment]
I have new problem after installation of gmt
gmt
gmt: error while loading shared libraries: libcfitsio.so.5: cannot open shared object file: No such file or directory

**Comment by mohseniaref-InSAR** [comment]
I fixed that issue by sudo apt-get install libcfit*

**Comment by leouieda** [comment]
Thanks for reporting @mohseniaref-InSAR! I'm glad that was sorted out.
