### ISSUE TITLE
Test 1 command error

### ISSUE THREAD

**Issue by zeigler1021** [GenericMappingTools/2019-unavco-course#18]
1. The command ./test_1.sh
2. I successfully cloned hw1 to my computer and found the path. I then typed the command, got a bunch of information about GMT (example commands, copyright, warranty, etc) and then got this error:
ERROR: No module named end was found.  This could mean one of three cases:
  1. There actually is no such module; please check your spelling.
  2. Module exists in the GMT supplemental library, but the library could not be found.
  3. Module exists in a GMT custom library, but none was specified via GMT_CUSTOM_LIBS.
Shared libraries must be in standard system paths or set via environmental parameter DYLD_LIBRARY_PATH.

**Operating system**: MacOS High Sierra 10.13.6

**Homework number**: HW 1

**Question**: How do I resolve the above error to produce the map?

**Comment by leouieda** [comment]
@zeigler1021 it's actually none of those options. It's in the core GMT and should be installed. This probably means that you have GMT 5 instead of GMT 6.0.0rc2. Please post the output of `gmt --version` so we can check.

**Comment by zeigler1021** [comment]
It is running 5.4.5, I installed version 6 successfully and it looked like it overwrote version 5 but clearly not. Is there an easy way to removed all version of GMT I currently have installed and just reinstall 6?
I got it work (aka I produced the map) but if there is a way to remove GMT 5 so that terminal doesn't default to that, that'd be great.

**Comment by leouieda** [comment]
@zeigler1021 did you already have GMT5 installed or was it mistakenly installed for the course?

**Comment by zeigler1021** [comment]
I had it previously installed and I thought when I installed 6 it had overwritten 5. I can access version 6 easily but getting rid of 5 would be helpful.

**Comment by leouieda** [comment]
Yep, you can probably remove 5 without much trouble. Do you by any chance remember how you installed it?

Pinging @PaulWessel and @seisman here since I've never used a Mac.

**Comment by PaulWessel** [comment]
Depends on how @zeigler1021 installed GMT 5.4.5 I think:

1. If you installed it via the Bundle installer, then just delete the GMT5.4.5 application from the Application folder
2. If you installed it via macports, fink or brew then try to run the uninstall command for that package manager, e.g., "sudo port uninstall gmt5" (ir macports).
3. If you built it yourself then you need to delete wherever it was put.

**Comment by zeigler1021** [comment]
I installed it via homebrew, I cannot seem to figure out the command to uninstall gmt5 but it's no big deal. I'll keep searching around. Thanks for your help!!

**Comment by leouieda** [comment]
Does `brew uninstall gmt` work?

**Comment by zeigler1021** [comment]
Yes it did!! Thank you so much, I really appreciate it! Now I am just left with GMT 6. Cheers!
