### ISSUE TITLE
Terminal cannot find gmt

### ISSUE THREAD

**Issue by amberjtucker** [GenericMappingTools/2019-unavco-course#21]
**Operating system**: MacOS Mojave 10.14.5

**Homework number**: 1 task 5

**Question**: 

I followed all of the steps for downloading GMT using Homebrewer, I did not have any errors or issues with the downloads, and I can see GMT in my applications folder. Was there a step I missed for linking GMT to everything?

**Comment by leouieda** [comment]
> Was there a step I missed for linking GMT to everything?

@amberjtucker what do you mean by that? What happens when you run `test_1.sh`?

**Comment by amberjtucker** [comment]
@leouieda when I ran test_1.sh it sent back :
./test_1.sh: line 3: gmt: command not found
./test_1.sh: line 4: gmt: command not found
./test_1.sh: line 5: gmt: command not found
./test_1.sh: line 6: gmt: command not found

But I fixed it! My path to the GMT application was incorrect; I was sending it to the wrong applications folder. 

I am now able to run test_1 and test_2.

**Comment by leouieda** [comment]
@amberjtucker that's great to hear! :+1:
