### ISSUE TITLE
Windows:  test_2.sh not generate count.mp4 or count.webm

### ISSUE THREAD

**Issue by francoloma** [GenericMappingTools/2019-unavco-course#24]
**Operating system**:  Windows 10 64-bit

**Homework number**: 2

**Question**:
$ ./test_2.sh
movie [ERROR]: Running ffmpeg conversion to MP4 returned error 1 - exiting.
Open either count.mp4 or count.webm in an application that can view movies

Is ffmpeg the problem?  How to test if I have ffmpeg installed properly?

I am in /c/2019-unavco-course/hw1

**Comment by francoloma** [comment]
I have the ffmpeg in this location /c/programs/gmt6/bin/ffmpeg

**Comment by francoloma** [comment]
RESOLVED.   The output wasn't in ./hw1 directory.  It was in ./hw1/output directory.

I successfully was able to generate animation.  Closing ticket.

**Comment by francoloma** [comment]
This might be bug.  The output from running ./test_2.sh seemed to say ffmpeg didn't work but it did,  just output in different directory

**Comment by seisman** [comment]
I can reproduce the issue with GMT 6.0.0rc3 on Windows.

@francoloma The MP4 movie you saw in the output directory is shipped by this repository, not generated by your script.

@joa-quim I added `-Vd` to the `gmt movie` commands, the error message is:
```
movie [INFORMATION]: Running: ffmpeg -loglevel warning -f image2 -framerate 4 -y -i "count/count_%02d.png" -vcodec libx264  -pix_fmt yuv420p count.mp4
[image2 @ 000001682C2523C0] Could not find codec parameters for stream 0 (Video: png, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Unknown encoder 'libx264'
movie [ERROR]: Running ffmpeg conversion to MP4 returned error 1 - exiting.
movie (gmtlib_free_tmp_arrays): tried to free unallocated memory
gmt.exe [DEBUG]: Entering GMT_Destroy_Session
```
It seems something wrong with your ffmpeg build or some .dll libraries are not included into the installer correctly.

**Comment by joa-quim** [comment]
Damn it. It works for me but I found why. I have ImageMagick fist in path and it has a standalone (static) ffmpeg.exe that does the job. 

I'm suspecting the lack of the *.ffpreset files by the Win installers.

**Comment by joa-quim** [comment]
Things are more complicated. Even if I rebuild ffmpeg with the libx264 (that was missing) it still errors with

```
movie [INFORMATION]: Running: ffmpeg -loglevel warning -f image2 -framerate 4 -y -i "count/count_%01d.png" -vcodec libx264  -pix_fmt yuv420p count.mp4
[image2 @ 00000264E4FE60C0] Could not find codec parameters for stream 0 (Video: png, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Decoder (codec png) not found for input stream #0:0
```

We can pass around a working ``ffmpeg.exe`` or people can install ImageMagick (that's where I got my good ``ffmpeg.exe``). Or download from ffmpeg site.

**Comment by francoloma** [comment]
I would need the working copy asap, as I do not have system admin privileges on my laptop

**Comment by joa-quim** [comment]
Replace the ``ffmpeg.exe`` that you have in ``C:\programs\gmt6\bin`` with the one in this zip file and all should be good.
In principle you don't need to have administrator privileges to do that.
 
[ffmpeg.zip](https://github.com/GenericMappingTools/2019-unavco-course/files/3411946/ffmpeg.zip)

**Comment by francoloma** [comment]
Success!  That fixed the ffmpeg issue.  

I was able to complete homework test 2.  Here you can see the file size difference:

08/29/2018  01:21 AM         37,541,432 ffmpeg.exe
07/10/2019  11:55 AM              313,856 ffmpeg.exe.bad

**Comment by joa-quim** [comment]
Yea, I know. The smaller one is a dynamic build one (it relies on some dlls) whilst the larger is a static build. 3x larger (than the first ensemble) ... but works.

**Comment by francoloma** [comment]
Joa-quim

You mentioned first release was missing libx264.   Do I need to re-install GMT or is the fix I did with ffmpeg sufficient?

**Comment by joa-quim** [comment]
No re-installs. The ``libx264`` was an attempt to rescue the dynamic build ``ffmpeg`` ... that failed miserably..
You are good to go with your current GMT.
