### ISSUE TITLE
Instructions for setting up computers

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/2019-unavco-course#3]
The GMT official instructions don't mention the rc1 and we'll need a bit more than that. We should have a document here with instructions for installing what we need:

* GMT 6.0.0rc1
* GMT dependencies? (maybe not needed)
* A text editor (we can recommend one and let people use their preferred if they have one)
* Bash (for Windows users)
* Other setup instructions (e.g., running something to download larger datasets prior to arrival)

**Comment by PaulWessel** [comment]
I installed Git for windows and GMT from @joa-quim 64-bit installer.  Opened up Git bash and ran some commands.  Worked as a charm.  This is a mingw based bash system it seems and most common tools we may need (awk, grep, sort, etc) are there.  This may be the simplest way for Windows GMT novices to install and use GMT.  When I tried gmt docs map.pdf (well, full path to map.pdf due to bug in r1) it opened up Acrobat Reader and displayed the map.

**Comment by joa-quim** [comment]
And the click-batch issue, can you reproduce it?

**Comment by PaulWessel** [comment]
No. I made a map.bat file and double clicked in the file explorer but nothing seems to happen.  Run as Administrator brings up a cmd window and the commands are executed (somewhere) and then the window closes.  I think it runs it in a system directory.  But just double-clicking for me has no affect, i.e., no system error as to why it cannot run it.

**Comment by joa-quim** [comment]
You can add a ``pause`` in last line to see if any error messages. But if no error you should see the map file.

**Comment by PaulWessel** [comment]
Thanks, it now says it cannot find gmt, so cmd.exe cannot find gmt and all commands fail.   Running the batch file in the command window works.   So at least for me, double-clicking runs the batch script without the same PATH as I have when I run it on the command line.  When I use run-as-administrator it finds the gmt executable; it is also running it in C:\WIndows\system32, while my double-clicking runs in my home directory.

**Comment by seisman** [comment]
That's weird. Double-clicking and running in command prompt both work for me.

**Comment by joa-quim** [comment]
Yes, never saw or heard anything like that. Can you make the batch print the path and environment variables to see how it compares with command line? Just add two lines with ``path`` and ``set``

**Comment by PaulWessel** [comment]
Must await Monday as I did not bring my Dell clunker home.

**Comment by joa-quim** [comment]
There is also one thing called ``Bootcamp`` that renders MacMachines useful

**Comment by PaulWessel** [comment]
Yes, I may consider that for my laptop for testing.  But I also don't haul my laptop home normally so does not solve that problem.  I run parallels at home on my iMac and have Windows so perhaps I can recreate it there.
